# Generated by Django 5.0.1 on 2024-02-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customersignupform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(max_length=50)),
                ('CEmail', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=50)),
            ],
        ),
    ]
