# Generated by Django 5.0.1 on 2024-02-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firoj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='availablecab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DName', models.CharField(max_length=50)),
                ('CNo', models.CharField(max_length=10)),
                ('DphNo', models.CharField(max_length=10)),
                ('CType', models.CharField(max_length=10)),
            ],
        ),
    ]
