# Generated by Django 5.0.1 on 2024-02-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firoj', '0002_availablecab'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(max_length=50)),
                ('CAddress', models.CharField(max_length=50)),
                ('CphNo', models.CharField(max_length=12)),
                ('CEmail', models.CharField(max_length=20)),
            ],
        ),
    ]
